// Generated by ailangc. Do not edit by hand.
// Expose POSIX/GNU declarations — clock_gettime + CLOCK_* (<time.h>) and
// getaddrinfo + struct addrinfo (<netdb.h>) — which glibc hides under
// `-std=c11` (it defines __STRICT_ANSI__). Must come before any #include.
// Harmless no-op on macOS/BSD libc, which expose these by default.
#define _GNU_SOURCE
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include <regex.h>
#include <time.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <sys/wait.h>
#include <gc.h>

/* -------- print/println -------- */
static inline void ailang_print_i64(int64_t v) { printf("%lld", (long long)v); }
static inline void ailang_println_i64(int64_t v) { printf("%lld\n", (long long)v); }
/* `int` is a distinct C11 type from `int64_t` even when both are 32/64 bits
 * on the current target. FFI return types like `int abs(int)` need this. */
static inline void ailang_print_int(int v) { printf("%d", v); }
static inline void ailang_println_int(int v) { printf("%d\n", v); }
static inline void ailang_print_f64(double v) { printf("%g", v); }
static inline void ailang_println_f64(double v) { printf("%g\n", v); }
static inline void ailang_print_bool(bool v) { printf("%s", v ? "true" : "false"); }
static inline void ailang_println_bool(bool v) { printf("%s\n", v ? "true" : "false"); }
static inline void ailang_print_str(const char* s) { printf("%s", s); }
static inline void ailang_println_str(const char* s) { printf("%s\n", s); }

/* -------- string operations (heap allocated via Boehm GC) --------
 *
 * Strings remain null-terminated `const char*` so they interoperate with C
 * libraries (printf, puts) without conversion. Allocation goes through
 * GC_malloc_atomic — the contents are bytes with no internal pointers,
 * so Boehm can skip scanning them, which is both faster and avoids spurious
 * retention.
 *
 * Length caching: `strlen()` is O(n), which makes naive `acc = acc + x`
 * loops O(n²) twice over (once for each strlen plus the memcpy). We keep
 * a tiny per-thread cache of recently-known (pointer, length) pairs so
 * `ailang_str_len` and the strlen calls inside `concat` short-circuit
 * when they recognize the pointer. Two slots: one for the last `concat`
 * result (hits the accumulator in `acc = acc + x` loops), one for the
 * last queried pointer (hits the other operand on the next iteration).
 *
 * Strings remain logically immutable — we never write past the existing
 * NUL, so the cached length stays accurate for the lifetime of the
 * pointer. The cache is a pure performance hint; correctness falls back
 * to `strlen` on a miss. */
static __thread const char* g_strlen_recent_concat = NULL;
static __thread int64_t g_strlen_recent_concat_len = 0;
static __thread const char* g_strlen_recent_query = NULL;
static __thread int64_t g_strlen_recent_query_len = 0;

static inline int64_t ailang_str_len(const char* s) {
    if (!s) return 0;
    if (s == g_strlen_recent_concat) return g_strlen_recent_concat_len;
    if (s == g_strlen_recent_query) return g_strlen_recent_query_len;
    int64_t n = (int64_t) strlen(s);
    g_strlen_recent_query = s;
    g_strlen_recent_query_len = n;
    return n;
}

static inline const char* ailang_str_concat(const char* a, const char* b) {
    int64_t la = ailang_str_len(a);
    int64_t lb = ailang_str_len(b);
    char* out = (char*) GC_malloc_atomic((size_t)(la + lb + 1));
    if (la) memcpy(out, a, (size_t)la);
    if (lb) memcpy(out + la, b, (size_t)lb);
    out[la + lb] = '\0';
    g_strlen_recent_concat = out;
    g_strlen_recent_concat_len = la + lb;
    return out;
}

/* -------- ailang_str_append: in-place append for self-assignment pattern --------
 *
 * Emitted ONLY by codegen for the syntactic form `x = x + y` (or `x += y`,
 * which desugars to the same AST). The compiler guarantees that `dst` on
 * the LHS is the same variable as the `a` operand on the RHS, so any
 * snapshot pointer the user took before this statement still observes the
 * pre-append bytes [0, old_len) intact — we only ever write at offsets
 * ≥ old_len.
 *
 * Mechanism: a per-thread "builder" buffer caches the last in-place-extended
 * string. If `a` matches it and there's spare cap, we mutate in place.
 * Otherwise we allocate a fresh buffer at 2× the needed size to seed the
 * builder. Result: `acc = acc + "y"` in a loop is amortized O(1) per call,
 * turning the classic O(n²) concat-accumulator into O(n).
 *
 * Aliasing caveat: if the user did `saved := acc` AFTER `acc` first became
 * a heap string (i.e., `saved` holds the builder pointer), a subsequent
 * `acc = acc + x` will extend the bytes past `saved`'s logical end. Any
 * read of `saved` via libc (`printf("%s")`, `strlen`, ...) walks until
 * `\0`, so it will see the appended bytes. Code that only uses `len(saved)`
 * + indexed reads stays correct because `saved` still snapshots the
 * intent — only nul-scanning APIs are affected. The risk is bounded:
 * regular `+` outside the self-assign pattern still goes through
 * `ailang_str_concat`, which always allocates fresh. */
static __thread char* g_strbuf = NULL;
static __thread int64_t g_strbuf_len = 0;
static __thread int64_t g_strbuf_cap = 0;

static const char* ailang_str_append(const char* a, const char* b) {
    int64_t lb = ailang_str_len(b);
    if (a == g_strbuf && a != NULL) {
        int64_t need = g_strbuf_len + lb;
        if (need + 1 <= g_strbuf_cap) {
            if (lb) memcpy(g_strbuf + g_strbuf_len, b, (size_t)lb);
            g_strbuf[need] = '\0';
            g_strbuf_len = need;
            g_strlen_recent_concat = g_strbuf;
            g_strlen_recent_concat_len = need;
            return g_strbuf;
        }
        int64_t new_cap = need * 2;
        if (new_cap < 32) new_cap = 32;
        char* new_buf = (char*) GC_malloc_atomic((size_t)(new_cap + 1));
        if (g_strbuf_len) memcpy(new_buf, g_strbuf, (size_t)g_strbuf_len);
        if (lb) memcpy(new_buf + g_strbuf_len, b, (size_t)lb);
        new_buf[need] = '\0';
        g_strbuf = new_buf;
        g_strbuf_len = need;
        g_strbuf_cap = new_cap;
        g_strlen_recent_concat = new_buf;
        g_strlen_recent_concat_len = need;
        return new_buf;
    }
    int64_t la = ailang_str_len(a);
    int64_t need = la + lb;
    int64_t new_cap = need * 2;
    if (new_cap < 32) new_cap = 32;
    char* new_buf = (char*) GC_malloc_atomic((size_t)(new_cap + 1));
    if (la) memcpy(new_buf, a, (size_t)la);
    if (lb) memcpy(new_buf + la, b, (size_t)lb);
    new_buf[need] = '\0';
    g_strbuf = new_buf;
    g_strbuf_len = need;
    g_strbuf_cap = new_cap;
    g_strlen_recent_concat = new_buf;
    g_strlen_recent_concat_len = need;
    return new_buf;
}

static inline int64_t ailang_str_at(const char* s, int64_t i) {
    return (int64_t)(unsigned char) s[i];
}

/* -------- string operations (M6++) --------
 *
 * All return GC-allocated strings (or arrays/bools). Indices are byte
 * offsets — these aren't Unicode-aware, just like libc.
 *
 * `contains/starts_with/ends_with/index_of/to_upper/to_lower/replace/
 *  trim/substring/split` are all here. `split` lives further down with
 *  the array helpers it depends on.
 */
static bool ailang_str_contains(const char* haystack, const char* needle) {
    if (!haystack || !needle) return false;
    return strstr(haystack, needle) != NULL;
}
static bool starts_with(const char* s, const char* prefix) {
    if (!s || !prefix) return false;
    size_t lp = strlen(prefix);
    return strncmp(s, prefix, lp) == 0;
}
static bool ends_with(const char* s, const char* suffix) {
    if (!s || !suffix) return false;
    size_t ls = strlen(s), lsu = strlen(suffix);
    if (lsu > ls) return false;
    return memcmp(s + ls - lsu, suffix, lsu) == 0;
}
static int64_t ailang_str_index_of(const char* haystack, const char* needle) {
    if (!haystack || !needle) return -1;
    const char* p = strstr(haystack, needle);
    return p ? (int64_t)(p - haystack) : (int64_t)-1;
}
static const char* to_upper(const char* s) {
    if (!s) return "";
    size_t n = strlen(s);
    char* out = (char*) GC_malloc_atomic(n + 1);
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char) s[i];
        out[i] = (c >= 'a' && c <= 'z') ? (char)(c - 32) : (char) c;
    }
    out[n] = '\0';
    return out;
}
static const char* to_lower(const char* s) {
    if (!s) return "";
    size_t n = strlen(s);
    char* out = (char*) GC_malloc_atomic(n + 1);
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char) s[i];
        out[i] = (c >= 'A' && c <= 'Z') ? (char)(c + 32) : (char) c;
    }
    out[n] = '\0';
    return out;
}
static const char* trim(const char* s) {
    if (!s) return "";
    const char* p = s;
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    const char* e = s + strlen(s);
    while (e > p) {
        char c = e[-1];
        if (c != ' ' && c != '\t' && c != '\n' && c != '\r') break;
        e--;
    }
    size_t n = (size_t)(e - p);
    char* out = (char*) GC_malloc_atomic(n + 1);
    memcpy(out, p, n);
    out[n] = '\0';
    return out;
}
/* `substring(s, start, end)` — bytes [start, end). Clamps to bounds. */
static const char* substring(const char* s, int64_t start, int64_t end) {
    if (!s) return "";
    int64_t n = (int64_t) strlen(s);
    if (start < 0) start = 0;
    if (end > n) end = n;
    if (end < start) end = start;
    size_t len = (size_t)(end - start);
    char* out = (char*) GC_malloc_atomic(len + 1);
    if (len) memcpy(out, s + start, len);
    out[len] = '\0';
    return out;
}
/* `replace(s, old, new)` — replace every non-overlapping occurrence. */
static const char* replace(const char* s, const char* old_, const char* new_) {
    if (!s || !old_ || !*old_) return s ? s : "";
    if (!new_) new_ = "";
    size_t lo = strlen(old_), ln = strlen(new_);
    /* Count occurrences for a single pre-sized allocation. */
    size_t count = 0;
    const char* p = s;
    while ((p = strstr(p, old_)) != NULL) { count++; p += lo; }
    size_t ls = strlen(s);
    size_t out_len = ls + count * (ln >= lo ? ln - lo : 0) - count * (lo > ln ? lo - ln : 0);
    char* out = (char*) GC_malloc_atomic(out_len + 1);
    char* w = out;
    const char* r = s;
    while ((p = strstr(r, old_)) != NULL) {
        size_t before = (size_t)(p - r);
        memcpy(w, r, before); w += before;
        memcpy(w, new_, ln); w += ln;
        r = p + lo;
    }
    size_t tail = strlen(r);
    memcpy(w, r, tail); w += tail;
    *w = '\0';
    return out;
}

/* -------- I/O + string conversion builtins (M6++) --------
 *
 * These appear as plain function names from AiLang user code (`read_file`,
 * `read_line`, `write_file`, `int_to_str`, `str_to_int`, `exit`, `args`).
 * Sema registers them so calls type-check; codegen emits the name verbatim
 * so each call lands on the C function defined here.
 *
 * All string results are GC-allocated so the caller has no manual lifetime
 * to track. Process-level state (argc/argv) is captured in `main`. */

static int    ailang_argc_ = 0;
static char** ailang_argv_ = NULL;

/* `read_file(path)` — slurp the whole file into a GC string; "" on error. */
static const char* read_file(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return "";
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return ""; }
    long n = ftell(f);
    if (n < 0) { fclose(f); return ""; }
    rewind(f);
    char* buf = (char*) GC_malloc_atomic((size_t)n + 1);
    size_t got = fread(buf, 1, (size_t)n, f);
    buf[got] = '\0';
    fclose(f);
    return buf;
}

/* `write_file(path, contents)` — overwrite the file; returns true on success. */
static bool write_file(const char* path, const char* contents) {
    FILE* f = fopen(path, "wb");
    if (!f) return false;
    size_t len = contents ? strlen(contents) : 0;
    size_t wrote = fwrite(contents, 1, len, f);
    fclose(f);
    return wrote == len;
}

/* `read_line()` — one stdin line, trailing '\n' stripped; "" on EOF. */
static const char* read_line(void) {
    /* Use a growing buffer instead of getline() so we don't pull in
     * platform-specific extensions (getline is POSIX-only). */
    size_t cap = 128, len = 0;
    char* buf = (char*) GC_malloc_atomic(cap);
    int c;
    while ((c = fgetc(stdin)) != EOF && c != '\n') {
        if (len + 1 >= cap) {
            size_t new_cap = cap * 2;
            char* nb = (char*) GC_malloc_atomic(new_cap);
            memcpy(nb, buf, len);
            buf = nb;
            cap = new_cap;
        }
        buf[len++] = (char) c;
    }
    buf[len] = '\0';
    if (len == 0 && c == EOF) return "";
    return buf;
}

/* `int_to_str(n)` — base-10 i64 → GC-allocated string. */
static const char* int_to_str(int64_t n) {
    char tmp[24];
    int len = snprintf(tmp, sizeof tmp, "%lld", (long long) n);
    char* out = (char*) GC_malloc_atomic((size_t)len + 1);
    memcpy(out, tmp, (size_t)len + 1);
    return out;
}

/* `str_to_int(s)` — parse leading integer; 0 if malformed (libc atoi). */
static int64_t str_to_int(const char* s) {
    return (int64_t) atoll(s ? s : "");
}

/* `float_to_str(x)` — base-10 f64 → GC-allocated string ("%g" format). */
static const char* float_to_str(double x) {
    char tmp[32];
    int len = snprintf(tmp, sizeof tmp, "%g", x);
    if (len < 0) len = 0;
    if (len >= (int)sizeof tmp) len = (int)sizeof tmp - 1;
    char* out = (char*) GC_malloc_atomic((size_t)len + 1);
    memcpy(out, tmp, (size_t)len + 1);
    return out;
}

/* `str_to_float(s)` — parse leading float; 0.0 if malformed (libc strtod). */
static double str_to_float(const char* s) {
    return s ? strtod(s, NULL) : 0.0;
}

/* `bool_to_str(b)` — "true" / "false". Targets of to_str's _Generic dispatch. */
static const char* bool_to_str(bool b) { return b ? "true" : "false"; }

/* Identity case so `to_str` works on values that are already strings. */
static const char* str_to_str(const char* s) { return s ? s : ""; }

/* `to_str(x)` — polymorphic stringify used by string interpolation
 * (`"hi ${name}"` desugars to `"hi " + to_str(name)`). The compile-time
 * _Generic picks the right helper; sema's expr_types isn't consulted, so
 * any value whose C type isn't listed here will fail to compile. */
#define to_str(__x) _Generic((__x), \
    int64_t: int_to_str, \
    int32_t: int_to_str, \
    int16_t: int_to_str, \
    int8_t:  int_to_str, \
    double:  float_to_str, \
    float:   float_to_str, \
    bool:    bool_to_str, \
    ailang_bytes: bytes_to_str, \
    char*:       str_to_str, \
    const char*: str_to_str \
)(__x)

/* `format(fmt, ...)` — printf-style formatting → GC-allocated string.
 * Caller is responsible for matching `%d`/`%lld`/`%s`/`%g` against the
 * actual arg types; sema marks this variadic so we don't type-check args. */
static const char* format(const char* fmt, ...) {
    char buf[1024];
    va_list ap;
    va_start(ap, fmt);
    int n = vsnprintf(buf, sizeof buf, fmt ? fmt : "", ap);
    va_end(ap);
    if (n < 0) n = 0;
    if (n >= (int)sizeof buf) n = (int)sizeof buf - 1;
    char* out = (char*) GC_malloc_atomic((size_t)n + 1);
    memcpy(out, buf, (size_t)n + 1);
    return out;
}

/* `exit(code)` — terminate the process. */
static void ailang_exit(int code) { exit(code); }
#define exit(c) ailang_exit((int)(c))

/* `get_env(name)` — read an environment variable; "" if unset. */
static const char* get_env(const char* name) {
    const char* v = name ? getenv(name) : NULL;
    return v ? v : "";
}

/* `abs_i64(n)` — i64 absolute value (libc `abs` is `int abs(int)`). */
static int64_t abs_i64(int64_t n) { return n < 0 ? -n : n; }

/* -------- time --------
 *
 * `now_ms` / `now_us` — wall-clock since Unix epoch. CAN go backwards if
 *     the system clock is adjusted; use for timestamps/logs only.
 * `mono_ms` — monotonic clock. Use for measuring durations / timeouts.
 * `sleep_ms` — block the current thread for at least `ms` milliseconds. */
static int64_t now_ms(void) {
    struct timespec ts;
    if (clock_gettime(CLOCK_REALTIME, &ts) != 0) return 0;
    return (int64_t) ts.tv_sec * 1000 + (int64_t) (ts.tv_nsec / 1000000);
}
static int64_t now_us(void) {
    struct timespec ts;
    if (clock_gettime(CLOCK_REALTIME, &ts) != 0) return 0;
    return (int64_t) ts.tv_sec * 1000000 + (int64_t) (ts.tv_nsec / 1000);
}
static int64_t mono_ms(void) {
    struct timespec ts;
    if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0) return 0;
    return (int64_t) ts.tv_sec * 1000 + (int64_t) (ts.tv_nsec / 1000000);
}
static void sleep_ms(int64_t ms) {
    if (ms <= 0) return;
    struct timespec ts;
    ts.tv_sec = (time_t) (ms / 1000);
    ts.tv_nsec = (long) ((ms % 1000) * 1000000);
    /* nanosleep can return early on signal; loop until full duration elapses. */
    while (nanosleep(&ts, &ts) == -1) { /* ts now holds remaining time */ }
}

/* `time_iso(ms)` — UTC ISO 8601 timestamp like "2026-05-27T14:30:00Z".
 * `ms` is Unix milliseconds (e.g. `now_ms()`). Returns "" on overflow. */
static const char* time_iso(int64_t ms) {
    time_t sec = (time_t) (ms / 1000);
    struct tm tmv;
    if (!gmtime_r(&sec, &tmv)) return "";
    char* buf = (char*) GC_malloc_atomic(32);
    size_t n = strftime(buf, 32, "%Y-%m-%dT%H:%M:%SZ", &tmv);
    if (n == 0) { buf[0] = '\0'; }
    return buf;
}

/* Forward-declare `ailang_bytes` so the socket helpers below can use it
 * before the full definition (which lives with the container-type block
 * further down the prelude). The shape must match exactly. */
typedef struct { int64_t len; const uint8_t* data; } ailang_bytes;

/* -------- TCP sockets (POSIX) --------
 *
 * Thin wrappers over BSD sockets. The AiLang user sees `int64_t` file
 * descriptors and `bytes` payloads — no `struct sockaddr` exposure. All
 * functions return -1 (or an empty bytes) on failure; check via
 * `fd < 0` / `len(b) == 0`. errno is not exposed yet.
 *
 * IPv4 only for now; IPv6 + `getaddrinfo` for hostnames lands later. */
static int64_t tcp_listen(const char* host, int64_t port) {
    if (!host || port <= 0 || port > 65535) return -1;
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) return -1;
    int yes = 1;
    /* SO_REUSEADDR so a quick restart doesn't bounce on TIME_WAIT. */
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes));
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons((uint16_t) port);
    if (host[0] == '\0' || strcmp(host, "0.0.0.0") == 0) {
        addr.sin_addr.s_addr = htonl(INADDR_ANY);
    } else if (inet_pton(AF_INET, host, &addr.sin_addr) != 1) {
        close(fd);
        return -1;
    }
    if (bind(fd, (struct sockaddr*) &addr, sizeof(addr)) < 0) {
        close(fd);
        return -1;
    }
    if (listen(fd, 128) < 0) {
        close(fd);
        return -1;
    }
    return (int64_t) fd;
}

static int64_t tcp_accept(int64_t fd) {
    struct sockaddr_in addr;
    socklen_t len = sizeof(addr);
    int client = accept((int) fd, (struct sockaddr*) &addr, &len);
    if (client < 0) return -1;
    return (int64_t) client;
}

static int64_t tcp_connect(const char* host, int64_t port) {
    if (!host || port <= 0 || port > 65535) return -1;
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) return -1;
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons((uint16_t) port);
    if (inet_pton(AF_INET, host, &addr.sin_addr) != 1) {
        /* Fall back to hostname resolution. */
        struct addrinfo hints;
        memset(&hints, 0, sizeof(hints));
        hints.ai_family = AF_INET;
        hints.ai_socktype = SOCK_STREAM;
        struct addrinfo* res = NULL;
        if (getaddrinfo(host, NULL, &hints, &res) != 0 || !res) {
            close(fd);
            return -1;
        }
        addr.sin_addr = ((struct sockaddr_in*) res->ai_addr)->sin_addr;
        freeaddrinfo(res);
    }
    if (connect(fd, (struct sockaddr*) &addr, sizeof(addr)) < 0) {
        close(fd);
        return -1;
    }
    return (int64_t) fd;
}

static int64_t sock_send(int64_t fd, ailang_bytes b) {
    if (fd < 0) return -1;
    if (b.len == 0) return 0;
    ssize_t n = send((int) fd, b.data, (size_t) b.len, 0);
    return (int64_t) n;
}

static int64_t sock_send_str(int64_t fd, const char* s) {
    if (fd < 0 || !s) return -1;
    size_t len = strlen(s);
    if (len == 0) return 0;
    ssize_t n = send((int) fd, s, len, 0);
    return (int64_t) n;
}

/* Reads up to `max` bytes. Returns empty bytes on EOF or error. */
static ailang_bytes sock_recv(int64_t fd, int64_t max) {
    ailang_bytes r;
    r.len = 0;
    r.data = (const uint8_t*) "";
    if (fd < 0 || max <= 0) return r;
    uint8_t* buf = (uint8_t*) GC_malloc_atomic((size_t) max);
    ssize_t n = recv((int) fd, buf, (size_t) max, 0);
    if (n <= 0) return r;
    r.len = (int64_t) n;
    r.data = buf;
    return r;
}

static int64_t sock_close(int64_t fd) {
    if (fd < 0) return 0;
    return (int64_t) close((int) fd);
}

/* -------- process management (POSIX fork-per-request model) --------
 *
 * `proc_fork` returns 0 in the child, the child's pid in the parent,
 * -1 on error. The child inherits all FDs and the parent's GC heap
 * (copy-on-write); each process then GCs independently.
 *
 * `proc_no_zombies` sets SIGCHLD to SIG_IGN so the kernel auto-reaps
 * exited children — the right default for accept-fork servers that
 * don't care about exit codes. Call once at startup. */
static int64_t proc_fork(void) {
    pid_t p = fork();
    return (int64_t) p;
}

static int64_t proc_getpid(void) {
    return (int64_t) getpid();
}

static void proc_no_zombies(void) {
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = SIG_IGN;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = SA_NOCLDWAIT;  /* kernel reaps, no zombies */
    sigaction(SIGCHLD, &sa, NULL);
}

/* Non-blocking reap of any exited children. Returns count reaped.
 * Useful when `proc_no_zombies` isn't set and you want manual control. */
static int64_t proc_reap(void) {
    int64_t n = 0;
    while (waitpid(-1, NULL, WNOHANG) > 0) n++;
    return n;
}

/* -------- `!T` result type (first slice of ADT support) --------
 *
 * One concrete `ailang_result_<T>` struct per primitive T. `ok(v)`
 * dispatches via `_Generic` on the wrapped value's type; `err_<T>(msg)`
 * is explicit per-T because the return type can't be inferred from a
 * string-only argument. `expr?` (Try) propagates errors to the
 * enclosing fn's return.
 *
 * Recursive / nested ADTs (general enums, e.g. `JsonValue`) still need
 * sum-type machinery — that's the next milestone past this one.
 */
typedef struct { bool ok; int64_t value; const char* error; } ailang_result_i64;
typedef struct { bool ok; const char* value; const char* error; } ailang_result_str;
typedef struct { bool ok; bool value; const char* error; } ailang_result_bool;
typedef struct { bool ok; double value; const char* error; } ailang_result_f64;

static inline ailang_result_i64  ok_i64(int64_t v)     { return (ailang_result_i64){true, v, ""}; }
static inline ailang_result_str  ok_str(const char* v) { return (ailang_result_str){true, v ? v : "", ""}; }
static inline ailang_result_bool ok_bool(bool v)       { return (ailang_result_bool){true, v, ""}; }
static inline ailang_result_f64  ok_f64(double v)      { return (ailang_result_f64){true, v, ""}; }

static inline ailang_result_i64  err_i64(const char* m)  { return (ailang_result_i64){false, 0, m ? m : ""}; }
static inline ailang_result_str  err_str(const char* m)  { return (ailang_result_str){false, "", m ? m : ""}; }
static inline ailang_result_bool err_bool(const char* m) { return (ailang_result_bool){false, false, m ? m : ""}; }
static inline ailang_result_f64  err_f64(const char* m)  { return (ailang_result_f64){false, 0.0, m ? m : ""}; }

#define ok(v) _Generic((v), \
    int64_t: ok_i64, \
    int: ok_i64, \
    double: ok_f64, \
    bool: ok_bool, \
    char*: ok_str, \
    const char*: ok_str)(v)

/* unwrap — return the value if ok, else abort with the error message. */
static inline int64_t     ailang_unwrap_i64 (ailang_result_i64  r) { if (!r.ok) { fprintf(stderr, "unwrap: %s\n", r.error); exit(1); } return r.value; }
static inline const char* ailang_unwrap_str (ailang_result_str  r) { if (!r.ok) { fprintf(stderr, "unwrap: %s\n", r.error); exit(1); } return r.value; }
static inline bool        ailang_unwrap_bool(ailang_result_bool r) { if (!r.ok) { fprintf(stderr, "unwrap: %s\n", r.error); exit(1); } return r.value; }
static inline double      ailang_unwrap_f64 (ailang_result_f64  r) { if (!r.ok) { fprintf(stderr, "unwrap: %s\n", r.error); exit(1); } return r.value; }
#define unwrap(r) _Generic((r), \
    ailang_result_i64:  ailang_unwrap_i64, \
    ailang_result_str:  ailang_unwrap_str, \
    ailang_result_bool: ailang_unwrap_bool, \
    ailang_result_f64:  ailang_unwrap_f64)(r)

static inline bool ailang_is_ok_i64 (ailang_result_i64  r) { return r.ok; }
static inline bool ailang_is_ok_str (ailang_result_str  r) { return r.ok; }
static inline bool ailang_is_ok_bool(ailang_result_bool r) { return r.ok; }
static inline bool ailang_is_ok_f64 (ailang_result_f64  r) { return r.ok; }
#define is_ok(r) _Generic((r), \
    ailang_result_i64:  ailang_is_ok_i64, \
    ailang_result_str:  ailang_is_ok_str, \
    ailang_result_bool: ailang_is_ok_bool, \
    ailang_result_f64:  ailang_is_ok_f64)(r)
#define is_err(r) ((bool)!is_ok(r))

/* err_msg(r) — the error string (empty if r is ok). */
static inline const char* ailang_err_msg_i64 (ailang_result_i64  r) { return r.error ? r.error : ""; }
static inline const char* ailang_err_msg_str (ailang_result_str  r) { return r.error ? r.error : ""; }
static inline const char* ailang_err_msg_bool(ailang_result_bool r) { return r.error ? r.error : ""; }
static inline const char* ailang_err_msg_f64 (ailang_result_f64  r) { return r.error ? r.error : ""; }
#define err_msg(r) _Generic((r), \
    ailang_result_i64:  ailang_err_msg_i64, \
    ailang_result_str:  ailang_err_msg_str, \
    ailang_result_bool: ailang_err_msg_bool, \
    ailang_result_f64:  ailang_err_msg_f64)(r)

/* `regex_match(pat, text)` — true if POSIX extended regex `pat` matches
 * any substring of `text`. Invalid patterns silently return false. */
static bool regex_match(const char* pat, const char* text) {
    if (!pat || !text) return false;
    regex_t re;
    if (regcomp(&re, pat, REG_EXTENDED | REG_NOSUB) != 0) return false;
    int rc = regexec(&re, text, 0, NULL, 0);
    regfree(&re);
    return rc == 0;
}

/* `regex_find(pat, text)` — first matching substring, GC-allocated.
 * Returns "" if no match or invalid pattern. */
static const char* regex_find(const char* pat, const char* text) {
    if (!pat || !text) return "";
    regex_t re;
    if (regcomp(&re, pat, REG_EXTENDED) != 0) return "";
    regmatch_t m;
    int rc = regexec(&re, text, 1, &m, 0);
    regfree(&re);
    if (rc != 0 || m.rm_so < 0) return "";
    size_t len = (size_t)(m.rm_eo - m.rm_so);
    char* out = (char*) GC_malloc_atomic(len + 1);
    memcpy(out, text + m.rm_so, len);
    out[len] = '\0';
    return out;
}

/* -------- arrays (M4+): [T] for T = i64 / str --------
 *
 * Arrays are a struct-by-value (len + cap + data pointer). The backing
 * store is GC-allocated so it survives across function boundaries without
 * any user-side memory management. We keep struct-by-value so `_Generic`
 * can dispatch on the static type — pointers to different element types
 * would alias.
 *
 * Allocator choice: `[i64]` backing stores hold pure integers with no
 * embedded pointers, so they go through `GC_malloc_atomic` — Boehm then
 * marks the object as live without *scanning its contents*, which both
 * cuts collector work proportional to the buffer size and removes the
 * false-retention hazard of an integer payload that happens to look like
 * a heap address. We only ever read slots we've already written, so the
 * non-zeroing atomic allocator is safe. `[str]` stores hold `const char*`
 * elements that the collector MUST scan, so they stay on `GC_MALLOC`. The
 * same split applies to the map key/value arrays below; the `occupied`
 * bitmaps are also pointer-free, so they use `GC_malloc_atomic` plus an
 * explicit `memset(0)` (atomic memory is uninitialized, and the probe
 * loops rely on empty slots reading 0) — same zeroing cost as `GC_MALLOC`,
 * minus the per-collection scan. A `{i64:i64}` map is then scan-free.
 *
 * Semantics: like a Go slice / Rust Vec with header-by-value. `cap` tracks
 * the backing buffer's capacity so `push` can amortize via doubling
 * instead of reallocating on every call (which was the previous O(n²)
 * behavior for accumulator-style code). Two struct values may share a
 * backing buffer; writes past one view's `len` but within `cap` are
 * invisible to that view because iteration always uses `len`. */
typedef struct { int64_t len; int64_t cap; int64_t* data; } ailang_arr_i64;
typedef struct { int64_t len; int64_t cap; const char** data; } ailang_arr_str;

static inline ailang_arr_i64 ailang_arr_i64_make(int64_t n, const int64_t* src) {
    ailang_arr_i64 a;
    a.len = n;
    a.cap = n;
    a.data = (int64_t*) GC_malloc_atomic((size_t)n * sizeof(int64_t));
    for (int64_t i = 0; i < n; i++) a.data[i] = src[i];
    return a;
}
static inline ailang_arr_str ailang_arr_str_make(int64_t n, const char* const* src) {
    ailang_arr_str a;
    a.len = n;
    a.cap = n;
    a.data = (const char**) GC_MALLOC((size_t)n * sizeof(const char*));
    for (int64_t i = 0; i < n; i++) a.data[i] = src[i];
    return a;
}

static inline int64_t ailang_arr_i64_len(ailang_arr_i64 a) { return a.len; }
static inline int64_t ailang_arr_str_len(ailang_arr_str a) { return a.len; }
static inline int64_t ailang_arr_i64_at(ailang_arr_i64 a, int64_t i) { return a.data[i]; }
static inline const char* ailang_arr_str_at(ailang_arr_str a, int64_t i) { return a.data[i]; }

/* -------- bytes: binary buffer that may contain `\0`. --------
 *
 * `str` is a nul-terminated `const char*` and stops at the first `\0`, which
 * makes it unusable for HTTP request bodies, TCP buffers, binary files, etc.
 * `bytes` carries an explicit length so it can hold arbitrary octets.
 *
 * Same value-semantic shape as `ailang_arr_*` so `_Generic` can dispatch.
 *
 * Note: the `ailang_bytes` typedef is forward-declared earlier in the
 * prelude (next to the socket helpers); here we only attach the helpers
 * — defining the typedef twice would be a redefinition error. */

static inline int64_t ailang_bytes_len(ailang_bytes b) { return b.len; }
static inline int64_t bytes_at(ailang_bytes b, int64_t i) {
    if (i < 0 || i >= b.len) return 0;
    return (int64_t) b.data[i];
}
static inline ailang_bytes bytes_slice(ailang_bytes b, int64_t lo, int64_t hi) {
    if (lo < 0) lo = 0;
    if (hi > b.len) hi = b.len;
    if (lo > hi) lo = hi;
    int64_t n = hi - lo;
    ailang_bytes r;
    r.len = n;
    uint8_t* buf = (uint8_t*) GC_malloc_atomic((size_t)(n > 0 ? n : 1));
    if (n > 0) memcpy(buf, b.data + lo, (size_t)n);
    r.data = buf;
    return r;
}
static inline ailang_bytes str_to_bytes(const char* s) {
    ailang_bytes r;
    if (!s) { r.len = 0; r.data = (const uint8_t*) ""; return r; }
    size_t n = strlen(s);
    r.len = (int64_t) n;
    /* Borrow the underlying storage — the string is already GC-rooted by
     * its variable, so we don't need to copy. */
    r.data = (const uint8_t*) s;
    return r;
}
static inline const char* bytes_to_str(ailang_bytes b) {
    /* Copy + append nul. Truncates at first embedded `\0` from the C side,
     * but the underlying bytes are still intact if the caller keeps the
     * original `bytes` value around. */
    char* buf = (char*) GC_malloc_atomic((size_t)b.len + 1);
    if (b.len > 0) memcpy(buf, b.data, (size_t)b.len);
    buf[b.len] = '\0';
    return buf;
}

/* read_file_bytes(path) — slurp the whole file into a fresh GC-allocated
 * `bytes` value. Returns an empty bytes on error. */
static ailang_bytes read_file_bytes(const char* path) {
    ailang_bytes r;
    r.len = 0;
    r.data = (const uint8_t*) "";
    FILE* f = fopen(path, "rb");
    if (!f) return r;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return r; }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return r; }
    if (fseek(f, 0, SEEK_SET) != 0) { fclose(f); return r; }
    uint8_t* buf = (uint8_t*) GC_malloc_atomic((size_t)(sz > 0 ? sz : 1));
    size_t got = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    r.len = (int64_t) got;
    r.data = buf;
    return r;
}

/* write_file_bytes(path, b) — overwrite the file with raw bytes. true on success. */
static bool write_file_bytes(const char* path, ailang_bytes b) {
    FILE* f = fopen(path, "wb");
    if (!f) return false;
    size_t want = (size_t) b.len;
    size_t got = b.len > 0 ? fwrite(b.data, 1, want, f) : 0;
    int closed = fclose(f);
    return closed == 0 && got == want;
}

/* Pretty-print: shows printable ASCII verbatim, non-printable as `\xNN`. */
static void ailang_print_bytes(ailang_bytes b) {
    printf("b\"");
    for (int64_t i = 0; i < b.len; i++) {
        unsigned c = b.data[i];
        if (c == '"') printf("\\\"");
        else if (c == '\\') printf("\\\\");
        else if (c == '\n') printf("\\n");
        else if (c == '\r') printf("\\r");
        else if (c == '\t') printf("\\t");
        else if (c >= 0x20 && c < 0x7f) putchar((int) c);
        else printf("\\x%02x", c);
    }
    putchar('"');
}
static void ailang_println_bytes(ailang_bytes b) { ailang_print_bytes(b); putchar('\n'); }

/* Compound-literal-based ctors so `[1, 2, 3]` codegens to a one-liner. */
#define AILANG_ARR_I64(n, ...) ailang_arr_i64_make((n), (int64_t[]){__VA_ARGS__})
#define AILANG_ARR_STR(n, ...) ailang_arr_str_make((n), (const char*[]){__VA_ARGS__})

/* -------- closures (M6++): fat function-pointers --------
 *
 * Every AiLang lambda compiles to a `static` C function whose first
 * parameter is a `void* __env` (so the lifted body can reach captures
 * even when the lambda has none — non-capturing lambdas pass `NULL`).
 *
 * The runtime value of a lambda is a `ailang_closure_t { fn, env }`
 * pair. Every fn-pointer-typed param/local in user code is also
 * `ailang_closure_t`. Calls dispatch by casting `fn` to the right
 * signature and threading `env` through:
 *
 *     ((RET (*)(void*, P1, P2))c.fn)(c.env, a1, a2)
 *
 * `env` is GC-allocated. Captures snapshot the outer value by copy;
 * mutation of an outer `mu` after a lambda is constructed doesn't
 * propagate (an explicit ref type would land later).
 */
typedef struct {
    void* fn;
    void* env;
} ailang_closure_t;

/* push — amortized O(1) via 2x doubling. When `cap > len` the new element
 * is written in place and the same backing buffer is shared with the
 * caller's value (caller's `len` is unchanged because the struct is
 * passed by value, so they still see the old view). When `cap == len`
 * we grow to max(8, cap*2) and copy. */
static ailang_arr_i64 ailang_arr_i64_push(ailang_arr_i64 a, int64_t x) {
    if (a.cap > a.len) {
        a.data[a.len] = x;
        a.len += 1;
        return a;
    }
    int64_t new_cap = a.cap > 0 ? a.cap * 2 : 8;
    int64_t* new_data = (int64_t*) GC_malloc_atomic((size_t)new_cap * sizeof(int64_t));
    if (a.len) memcpy(new_data, a.data, (size_t)a.len * sizeof(int64_t));
    new_data[a.len] = x;
    ailang_arr_i64 b;
    b.len = a.len + 1;
    b.cap = new_cap;
    b.data = new_data;
    return b;
}
static ailang_arr_str ailang_arr_str_push(ailang_arr_str a, const char* x) {
    if (a.cap > a.len) {
        a.data[a.len] = x;
        a.len += 1;
        return a;
    }
    int64_t new_cap = a.cap > 0 ? a.cap * 2 : 8;
    const char** new_data = (const char**) GC_MALLOC((size_t)new_cap * sizeof(const char*));
    if (a.len) memcpy(new_data, a.data, (size_t)a.len * sizeof(const char*));
    new_data[a.len] = x;
    ailang_arr_str b;
    b.len = a.len + 1;
    b.cap = new_cap;
    b.data = new_data;
    return b;
}
/* pop — just decrements the view's len; the backing buffer is unchanged. */
static ailang_arr_i64 ailang_arr_i64_pop(ailang_arr_i64 a) {
    if (a.len > 0) a.len -= 1;
    return a;
}
static ailang_arr_str ailang_arr_str_pop(ailang_arr_str a) {
    if (a.len > 0) a.len -= 1;
    return a;
}
#define push(arr, x) _Generic((arr), \
    ailang_arr_i64: ailang_arr_i64_push, \
    ailang_arr_str: ailang_arr_str_push)((arr), (x))
#define pop(arr) _Generic((arr), \
    ailang_arr_i64: ailang_arr_i64_pop, \
    ailang_arr_str: ailang_arr_str_pop)((arr))

/* sort / reverse / contains / index_of for arrays.
 *
 * sort: ascending, qsort-based, returns a fresh array (the input is
 * left alone so callers don't have to think about aliasing).
 * reverse: also returns a fresh array.
 * contains / index_of: linear scan. `index_of` returns -1 when missing.
 */
static int ailang_cmp_i64(const void* a, const void* b) {
    int64_t x = *(const int64_t*)a, y = *(const int64_t*)b;
    return (x > y) - (x < y);
}
static int ailang_cmp_str(const void* a, const void* b) {
    const char* x = *(const char* const*)a;
    const char* y = *(const char* const*)b;
    return strcmp(x ? x : "", y ? y : "");
}

static ailang_arr_i64 ailang_arr_i64_sort(ailang_arr_i64 a) {
    ailang_arr_i64 b;
    b.len = a.len;
    b.cap = a.len;
    b.data = (int64_t*) GC_malloc_atomic((size_t)(b.len > 0 ? b.len : 1) * sizeof(int64_t));
    if (b.len) memcpy(b.data, a.data, (size_t)b.len * sizeof(int64_t));
    if (b.len > 1) qsort(b.data, (size_t)b.len, sizeof(int64_t), ailang_cmp_i64);
    return b;
}
static ailang_arr_str ailang_arr_str_sort(ailang_arr_str a) {
    ailang_arr_str b;
    b.len = a.len;
    b.cap = a.len;
    b.data = (const char**) GC_MALLOC((size_t)(b.len > 0 ? b.len : 1) * sizeof(const char*));
    if (b.len) memcpy((void*)b.data, a.data, (size_t)b.len * sizeof(const char*));
    if (b.len > 1) qsort((void*)b.data, (size_t)b.len, sizeof(const char*), ailang_cmp_str);
    return b;
}

static ailang_arr_i64 ailang_arr_i64_reverse(ailang_arr_i64 a) {
    ailang_arr_i64 b;
    b.len = a.len;
    b.cap = a.len;
    b.data = (int64_t*) GC_malloc_atomic((size_t)(b.len > 0 ? b.len : 1) * sizeof(int64_t));
    for (int64_t i = 0; i < b.len; i++) b.data[i] = a.data[b.len - 1 - i];
    return b;
}
static ailang_arr_str ailang_arr_str_reverse(ailang_arr_str a) {
    ailang_arr_str b;
    b.len = a.len;
    b.cap = a.len;
    b.data = (const char**) GC_MALLOC((size_t)(b.len > 0 ? b.len : 1) * sizeof(const char*));
    for (int64_t i = 0; i < b.len; i++) b.data[i] = a.data[b.len - 1 - i];
    return b;
}

static bool ailang_arr_i64_contains(ailang_arr_i64 a, int64_t x) {
    for (int64_t i = 0; i < a.len; i++) if (a.data[i] == x) return true;
    return false;
}
static bool ailang_arr_str_contains(ailang_arr_str a, const char* x) {
    for (int64_t i = 0; i < a.len; i++) {
        if (a.data[i] == x) return true;
        if (a.data[i] && x && strcmp(a.data[i], x) == 0) return true;
    }
    return false;
}

static int64_t ailang_arr_i64_index_of(ailang_arr_i64 a, int64_t x) {
    for (int64_t i = 0; i < a.len; i++) if (a.data[i] == x) return i;
    return -1;
}
static int64_t ailang_arr_str_index_of(ailang_arr_str a, const char* x) {
    for (int64_t i = 0; i < a.len; i++) {
        if (a.data[i] == x) return i;
        if (a.data[i] && x && strcmp(a.data[i], x) == 0) return i;
    }
    return -1;
}

#define sort(arr) _Generic((arr), \
    ailang_arr_i64: ailang_arr_i64_sort, \
    ailang_arr_str: ailang_arr_str_sort)((arr))

#define reverse(arr) _Generic((arr), \
    ailang_arr_i64: ailang_arr_i64_reverse, \
    ailang_arr_str: ailang_arr_str_reverse)((arr))

#define contains(coll, x) _Generic((coll), \
    char*: ailang_str_contains, \
    const char*: ailang_str_contains, \
    ailang_arr_i64: ailang_arr_i64_contains, \
    ailang_arr_str: ailang_arr_str_contains)((coll), (x))

#define index_of(coll, x) _Generic((coll), \
    char*: ailang_str_index_of, \
    const char*: ailang_str_index_of, \
    ailang_arr_i64: ailang_arr_i64_index_of, \
    ailang_arr_str: ailang_arr_str_index_of)((coll), (x))

/* Higher-order helpers. v1: [i64] and [str] element types. Each callback
 * is an `ailang_closure_t`, dispatched through (*f.fn)(f.env, …). */
static ailang_arr_i64 ailang_arr_i64_map(ailang_arr_i64 a, ailang_closure_t f) {
    typedef int64_t (*FN)(void*, int64_t);
    FN fp = (FN) f.fn;
    ailang_arr_i64 b;
    b.len = a.len;
    b.cap = a.len;
    b.data = (int64_t*) GC_malloc_atomic((size_t)(b.len > 0 ? b.len : 1) * sizeof(int64_t));
    for (int64_t i = 0; i < a.len; i++) b.data[i] = fp(f.env, a.data[i]);
    return b;
}
static ailang_arr_i64 ailang_arr_i64_filter(ailang_arr_i64 a, ailang_closure_t pred) {
    typedef bool (*FN)(void*, int64_t);
    FN fp = (FN) pred.fn;
    ailang_arr_i64 b;
    b.data = (int64_t*) GC_malloc_atomic((size_t)(a.len > 0 ? a.len : 1) * sizeof(int64_t));
    int64_t n = 0;
    for (int64_t i = 0; i < a.len; i++) {
        if (fp(pred.env, a.data[i])) b.data[n++] = a.data[i];
    }
    b.len = n;
    b.cap = a.len;
    return b;
}
static int64_t ailang_arr_i64_reduce(ailang_arr_i64 a, int64_t init, ailang_closure_t f) {
    typedef int64_t (*FN)(void*, int64_t, int64_t);
    FN fp = (FN) f.fn;
    int64_t acc = init;
    for (int64_t i = 0; i < a.len; i++) acc = fp(f.env, acc, a.data[i]);
    return acc;
}

static ailang_arr_str ailang_arr_str_map(ailang_arr_str a, ailang_closure_t f) {
    typedef const char* (*FN)(void*, const char*);
    FN fp = (FN) f.fn;
    ailang_arr_str b;
    b.len = a.len;
    b.cap = a.len;
    b.data = (const char**) GC_MALLOC((size_t)(b.len > 0 ? b.len : 1) * sizeof(const char*));
    for (int64_t i = 0; i < a.len; i++) b.data[i] = fp(f.env, a.data[i]);
    return b;
}
static ailang_arr_str ailang_arr_str_filter(ailang_arr_str a, ailang_closure_t pred) {
    typedef bool (*FN)(void*, const char*);
    FN fp = (FN) pred.fn;
    ailang_arr_str b;
    b.data = (const char**) GC_MALLOC((size_t)(a.len > 0 ? a.len : 1) * sizeof(const char*));
    int64_t n = 0;
    for (int64_t i = 0; i < a.len; i++) {
        if (fp(pred.env, a.data[i])) b.data[n++] = a.data[i];
    }
    b.len = n;
    b.cap = a.len;
    return b;
}
/* reduce on [str]: accumulator is i64. */
static int64_t ailang_arr_str_reduce(ailang_arr_str a, int64_t init, ailang_closure_t f) {
    typedef int64_t (*FN)(void*, int64_t, const char*);
    FN fp = (FN) f.fn;
    int64_t acc = init;
    for (int64_t i = 0; i < a.len; i++) acc = fp(f.env, acc, a.data[i]);
    return acc;
}

#define map(arr, f) _Generic((arr), \
    ailang_arr_i64: ailang_arr_i64_map, \
    ailang_arr_str: ailang_arr_str_map)((arr), (f))
#define filter(arr, p) _Generic((arr), \
    ailang_arr_i64: ailang_arr_i64_filter, \
    ailang_arr_str: ailang_arr_str_filter)((arr), (p))
#define reduce(arr, init, f) _Generic((arr), \
    ailang_arr_i64: ailang_arr_i64_reduce, \
    ailang_arr_str: ailang_arr_str_reduce)((arr), (init), (f))

/* slice(arr, start, end) — half-open `[start, end)`. Clamps to bounds. */
static ailang_arr_i64 ailang_arr_i64_slice(ailang_arr_i64 a, int64_t start, int64_t end) {
    if (start < 0) start = 0;
    if (end > a.len) end = a.len;
    if (end < start) end = start;
    ailang_arr_i64 b;
    b.len = end - start;
    b.cap = b.len;
    b.data = (int64_t*) GC_malloc_atomic((size_t)(b.len > 0 ? b.len : 1) * sizeof(int64_t));
    if (b.len) memcpy(b.data, a.data + start, (size_t)b.len * sizeof(int64_t));
    return b;
}
static ailang_arr_str ailang_arr_str_slice(ailang_arr_str a, int64_t start, int64_t end) {
    if (start < 0) start = 0;
    if (end > a.len) end = a.len;
    if (end < start) end = start;
    ailang_arr_str b;
    b.len = end - start;
    b.cap = b.len;
    b.data = (const char**) GC_MALLOC((size_t)(b.len > 0 ? b.len : 1) * sizeof(const char*));
    if (b.len) memcpy((void*)b.data, a.data + start, (size_t)b.len * sizeof(const char*));
    return b;
}
#define slice(arr, start, end) _Generic((arr), \
    ailang_arr_i64: ailang_arr_i64_slice, \
    ailang_arr_str: ailang_arr_str_slice)((arr), (start), (end))

/* join — sep-delimited concatenation of an array.
 * For [i64], each element is formatted via "%lld". For [str], the
 * elements concatenate as-is (NULL→""). Returns a fresh GC string. */
static const char* ailang_arr_str_join(ailang_arr_str a, const char* sep) {
    if (!sep) sep = "";
    size_t sep_len = strlen(sep);
    size_t total = 0;
    for (int64_t i = 0; i < a.len; i++) total += a.data[i] ? strlen(a.data[i]) : 0;
    if (a.len > 1) total += sep_len * (size_t)(a.len - 1);
    char* out = (char*) GC_malloc_atomic(total + 1);
    char* w = out;
    for (int64_t i = 0; i < a.len; i++) {
        if (i > 0 && sep_len) { memcpy(w, sep, sep_len); w += sep_len; }
        const char* s = a.data[i] ? a.data[i] : "";
        size_t n = strlen(s);
        if (n) { memcpy(w, s, n); w += n; }
    }
    *w = '\0';
    return out;
}
static const char* ailang_arr_i64_join(ailang_arr_i64 a, const char* sep) {
    if (!sep) sep = "";
    size_t sep_len = strlen(sep);
    /* Worst-case: each i64 needs ≤ 21 chars (sign + 20 digits + nul). */
    size_t cap = (size_t)a.len * 22 + (a.len > 1 ? sep_len * (size_t)(a.len - 1) : 0) + 1;
    if (cap < 16) cap = 16;
    char* out = (char*) GC_malloc_atomic(cap);
    char* w = out;
    for (int64_t i = 0; i < a.len; i++) {
        if (i > 0 && sep_len) { memcpy(w, sep, sep_len); w += sep_len; }
        int n = snprintf(w, cap - (size_t)(w - out), "%lld", (long long) a.data[i]);
        if (n > 0) w += n;
    }
    *w = '\0';
    return out;
}
#define join(arr, sep) _Generic((arr), \
    ailang_arr_i64: ailang_arr_i64_join, \
    ailang_arr_str: ailang_arr_str_join)((arr), (sep))

/* repeat / pad — GC-allocated string outputs. */
static const char* repeat(const char* s, int64_t n) {
    if (!s || n <= 0) return "";
    size_t one = strlen(s);
    size_t total = one * (size_t)n;
    char* out = (char*) GC_malloc_atomic(total + 1);
    for (int64_t i = 0; i < n; i++) memcpy(out + (size_t)i * one, s, one);
    out[total] = '\0';
    return out;
}
static const char* pad_left(const char* s, int64_t width, const char* pad) {
    if (!s) s = "";
    if (!pad || !*pad) pad = " ";
    size_t slen = strlen(s);
    if ((int64_t)slen >= width) {
        char* out = (char*) GC_malloc_atomic(slen + 1);
        memcpy(out, s, slen + 1);
        return out;
    }
    size_t plen = strlen(pad);
    size_t need = (size_t)width - slen;
    char* out = (char*) GC_malloc_atomic((size_t)width + 1);
    size_t i = 0;
    while (i < need) { out[i] = pad[i % plen]; i++; }
    memcpy(out + need, s, slen);
    out[width] = '\0';
    return out;
}
static const char* pad_right(const char* s, int64_t width, const char* pad) {
    if (!s) s = "";
    if (!pad || !*pad) pad = " ";
    size_t slen = strlen(s);
    if ((int64_t)slen >= width) {
        char* out = (char*) GC_malloc_atomic(slen + 1);
        memcpy(out, s, slen + 1);
        return out;
    }
    size_t plen = strlen(pad);
    char* out = (char*) GC_malloc_atomic((size_t)width + 1);
    memcpy(out, s, slen);
    size_t i = slen;
    while (i < (size_t)width) { out[i] = pad[(i - slen) % plen]; i++; }
    out[width] = '\0';
    return out;
}

/* chr(i) — single-byte string. ord(s) — first byte of s (0 if empty). */
static const char* chr(int64_t i) {
    char* out = (char*) GC_malloc_atomic(2);
    out[0] = (char)(i & 0xFF);
    out[1] = '\0';
    return out;
}
static int64_t ord(const char* s) {
    return (s && *s) ? (int64_t)(unsigned char) s[0] : 0;
}

/* str_to_bool — "true"/"True"/"1"/"yes" → true; everything else false. */
static bool str_to_bool(const char* s) {
    if (!s) return false;
    if (strcmp(s, "true") == 0) return true;
    if (strcmp(s, "True") == 0) return true;
    if (strcmp(s, "TRUE") == 0) return true;
    if (strcmp(s, "1") == 0) return true;
    if (strcmp(s, "yes") == 0) return true;
    return false;
}

/* Misc numeric helpers. */
static double abs_f64(double x) { return x < 0 ? -x : x; }
/* `abs(x)` is now polymorphic — dispatch happens in codegen by looking at
 * the arg type (i64 → abs_i64, f64 → abs_f64). No C macro because that
 * would shadow user `ex fn abs(...)` declarations against libc. */
static int64_t sign(int64_t n) { return (n > 0) - (n < 0); }
static int64_t clamp(int64_t n, int64_t lo, int64_t hi) {
    if (n < lo) return lo;
    if (n > hi) return hi;
    return n;
}

/* `split(s, sep)` — split a string by a literal separator (not regex) into
 * a `[str]`. Empty separator returns `[s]` (no-op). Adjacent separators
 * produce empty strings, mirroring Python's `s.split(sep)`. */
static ailang_arr_str split(const char* s, const char* sep) {
    if (!s) s = "";
    if (!sep || !*sep) {
        ailang_arr_str a;
        a.len = 1;
        a.cap = 1;
        a.data = (const char**) GC_MALLOC(sizeof(const char*));
        a.data[0] = s;
        return a;
    }
    size_t lsep = strlen(sep);
    /* count pieces */
    int64_t pieces = 1;
    const char* p = s;
    while ((p = strstr(p, sep)) != NULL) { pieces++; p += lsep; }
    ailang_arr_str a;
    a.len = pieces;
    a.cap = pieces;
    a.data = (const char**) GC_MALLOC((size_t)pieces * sizeof(const char*));
    const char* r = s;
    int64_t i = 0;
    while ((p = strstr(r, sep)) != NULL) {
        size_t n = (size_t)(p - r);
        char* piece = (char*) GC_malloc_atomic(n + 1);
        memcpy(piece, r, n);
        piece[n] = '\0';
        a.data[i++] = piece;
        r = p + lsep;
    }
    /* trailing piece */
    size_t n = strlen(r);
    char* piece = (char*) GC_malloc_atomic(n + 1);
    memcpy(piece, r, n + 1);
    a.data[i] = piece;
    return a;
}

/* `args()` — argv[1..] as `[str]`. argc/argv captured in main(). */
static ailang_arr_str args(void) {
    int64_t n = ailang_argc_ > 1 ? (int64_t)(ailang_argc_ - 1) : 0;
    ailang_arr_str a;
    a.len = n;
    a.cap = n;
    a.data = (const char**) GC_MALLOC((size_t)(n > 0 ? n : 1) * sizeof(const char*));
    for (int64_t i = 0; i < n; i++) a.data[i] = ailang_argv_[i + 1];
    return a;
}

#define len(x) _Generic((x), \
    char*: ailang_str_len, \
    const char*: ailang_str_len, \
    ailang_bytes: ailang_bytes_len, \
    ailang_arr_i64: ailang_arr_i64_len, \
    ailang_arr_str: ailang_arr_str_len, \
    ailang_map_ii: ailang_map_ii_len, \
    ailang_map_si: ailang_map_si_len, \
    ailang_map_ss: ailang_map_ss_len)(x)

/* `has(m, k)` — map-only membership check. */
#define has(m, k) _Generic((m), \
    ailang_map_ii: ailang_map_ii_has, \
    ailang_map_si: ailang_map_si_has, \
    ailang_map_ss: ailang_map_ss_has)((m), (k))

/* -------- maps (M4+): {K:V} as open-addressing hash tables --------
 *
 * For M4+ we ship a single key/value combo: `{i64:i64}`. Mixed-type maps and
 * string-keyed maps land in a follow-up — the codegen path is already
 * structured around per-(K,V) function families, so it's an additive change.
 *
 * Maps are *reference* values (struct pointer) so `m[k] = v` mutates in
 * place. Allocation goes through GC_MALLOC; the underlying arrays are
 * resized in-place when load factor exceeds 0.7. */
typedef struct {
    int64_t cap;
    int64_t len;
    int64_t* keys;
    int64_t* values;
    uint8_t* occupied;
} ailang_map_ii_storage;
typedef ailang_map_ii_storage* ailang_map_ii;

static inline uint64_t ailang_hash_i64(int64_t k) {
    uint64_t x = (uint64_t)k;
    x ^= x >> 30;
    x *= 0xbf58476d1ce4e5b9ULL;
    x ^= x >> 27;
    x *= 0x94d049bb133111ebULL;
    x ^= x >> 31;
    return x;
}

static ailang_map_ii ailang_map_ii_make(int64_t initial_cap) {
    int64_t cap = 8;
    while (cap < initial_cap) cap *= 2;
    ailang_map_ii m = (ailang_map_ii) GC_MALLOC(sizeof(ailang_map_ii_storage));
    m->cap = cap;
    m->len = 0;
    m->keys = (int64_t*) GC_malloc_atomic((size_t)cap * sizeof(int64_t));
    m->values = (int64_t*) GC_malloc_atomic((size_t)cap * sizeof(int64_t));
    m->occupied = (uint8_t*) GC_malloc_atomic((size_t)cap);
    memset(m->occupied, 0, (size_t)cap);
    return m;
}

static void ailang_map_ii_grow(ailang_map_ii m) {
    int64_t old_cap = m->cap;
    int64_t* old_keys = m->keys;
    int64_t* old_values = m->values;
    uint8_t* old_occupied = m->occupied;
    int64_t new_cap = old_cap * 2;
    m->cap = new_cap;
    m->keys = (int64_t*) GC_malloc_atomic((size_t)new_cap * sizeof(int64_t));
    m->values = (int64_t*) GC_malloc_atomic((size_t)new_cap * sizeof(int64_t));
    m->occupied = (uint8_t*) GC_malloc_atomic((size_t)new_cap);
    memset(m->occupied, 0, (size_t)new_cap);
    uint64_t mask = (uint64_t)(new_cap - 1);
    for (int64_t i = 0; i < old_cap; i++) {
        if (!old_occupied[i]) continue;
        int64_t k = old_keys[i];
        uint64_t h = ailang_hash_i64(k) & mask;
        for (int64_t p = 0; p < new_cap; p++) {
            int64_t j = (int64_t)((h + (uint64_t)p) & mask);
            if (!m->occupied[j]) {
                m->keys[j] = k;
                m->values[j] = old_values[i];
                m->occupied[j] = 1;
                break;
            }
        }
    }
}

static void ailang_map_ii_set(ailang_map_ii m, int64_t k, int64_t v) {
    if (m->len * 10 >= m->cap * 7) ailang_map_ii_grow(m);
    uint64_t mask = (uint64_t)(m->cap - 1);
    uint64_t h = ailang_hash_i64(k) & mask;
    for (int64_t p = 0; p < m->cap; p++) {
        int64_t i = (int64_t)((h + (uint64_t)p) & mask);
        if (!m->occupied[i]) {
            m->keys[i] = k;
            m->values[i] = v;
            m->occupied[i] = 1;
            m->len++;
            return;
        }
        if (m->keys[i] == k) { m->values[i] = v; return; }
    }
}

static int64_t ailang_map_ii_get(ailang_map_ii m, int64_t k) {
    uint64_t mask = (uint64_t)(m->cap - 1);
    uint64_t h = ailang_hash_i64(k) & mask;
    for (int64_t p = 0; p < m->cap; p++) {
        int64_t i = (int64_t)((h + (uint64_t)p) & mask);
        if (!m->occupied[i]) return 0;
        if (m->keys[i] == k) return m->values[i];
    }
    return 0;
}

static int64_t ailang_map_ii_len(ailang_map_ii m) { return m->len; }
static bool ailang_map_ii_has(ailang_map_ii m, int64_t k) {
    uint64_t mask = (uint64_t)(m->cap - 1);
    uint64_t h = ailang_hash_i64(k) & mask;
    for (int64_t p = 0; p < m->cap; p++) {
        int64_t i = (int64_t)((h + (uint64_t)p) & mask);
        if (!m->occupied[i]) return false;
        if (m->keys[i] == k) return true;
    }
    return false;
}

/* -------- {str:i64} map — same shape as {i64:i64}, FNV-1a key hashing.
 *
 * Useful instantiation for word counters / configuration tables. Mirrors
 * the ii layout so the runtime cost story is identical; only the key type
 * and hash differ. */
typedef struct {
    int64_t cap;
    int64_t len;
    const char** keys;   /* NULL when slot is empty */
    int64_t* values;
    uint8_t* occupied;
} ailang_map_si_storage;
typedef ailang_map_si_storage* ailang_map_si;

static inline uint64_t ailang_hash_str(const char* s) {
    /* FNV-1a 64-bit. */
    uint64_t h = 0xcbf29ce484222325ULL;
    if (!s) return h;
    while (*s) { h ^= (uint64_t)(unsigned char) *s++; h *= 0x100000001b3ULL; }
    return h;
}

static ailang_map_si ailang_map_si_make(int64_t initial_cap) {
    int64_t cap = 8;
    while (cap < initial_cap) cap *= 2;
    ailang_map_si m = (ailang_map_si) GC_MALLOC(sizeof(ailang_map_si_storage));
    m->cap = cap;
    m->len = 0;
    m->keys = (const char**) GC_MALLOC((size_t)cap * sizeof(const char*));
    m->values = (int64_t*) GC_malloc_atomic((size_t)cap * sizeof(int64_t));
    m->occupied = (uint8_t*) GC_malloc_atomic((size_t)cap);
    memset(m->occupied, 0, (size_t)cap);
    return m;
}

static void ailang_map_si_grow(ailang_map_si m) {
    int64_t old_cap = m->cap;
    const char** old_keys = m->keys;
    int64_t* old_values = m->values;
    uint8_t* old_occupied = m->occupied;
    int64_t new_cap = old_cap * 2;
    m->cap = new_cap;
    m->keys = (const char**) GC_MALLOC((size_t)new_cap * sizeof(const char*));
    m->values = (int64_t*) GC_malloc_atomic((size_t)new_cap * sizeof(int64_t));
    m->occupied = (uint8_t*) GC_malloc_atomic((size_t)new_cap);
    memset(m->occupied, 0, (size_t)new_cap);
    uint64_t mask = (uint64_t)(new_cap - 1);
    for (int64_t i = 0; i < old_cap; i++) {
        if (!old_occupied[i]) continue;
        const char* k = old_keys[i];
        uint64_t h = ailang_hash_str(k) & mask;
        for (int64_t p = 0; p < new_cap; p++) {
            int64_t j = (int64_t)((h + (uint64_t)p) & mask);
            if (!m->occupied[j]) {
                m->keys[j] = k;
                m->values[j] = old_values[i];
                m->occupied[j] = 1;
                break;
            }
        }
    }
}

static void ailang_map_si_set(ailang_map_si m, const char* k, int64_t v) {
    if (m->len * 10 >= m->cap * 7) ailang_map_si_grow(m);
    uint64_t mask = (uint64_t)(m->cap - 1);
    uint64_t h = ailang_hash_str(k) & mask;
    for (int64_t p = 0; p < m->cap; p++) {
        int64_t i = (int64_t)((h + (uint64_t)p) & mask);
        if (!m->occupied[i]) {
            m->keys[i] = k;
            m->values[i] = v;
            m->occupied[i] = 1;
            m->len++;
            return;
        }
        if (strcmp(m->keys[i], k) == 0) { m->values[i] = v; return; }
    }
}

static int64_t ailang_map_si_get(ailang_map_si m, const char* k) {
    uint64_t mask = (uint64_t)(m->cap - 1);
    uint64_t h = ailang_hash_str(k) & mask;
    for (int64_t p = 0; p < m->cap; p++) {
        int64_t i = (int64_t)((h + (uint64_t)p) & mask);
        if (!m->occupied[i]) return 0;
        if (strcmp(m->keys[i], k) == 0) return m->values[i];
    }
    return 0;
}

static int64_t ailang_map_si_len(ailang_map_si m) { return m->len; }
static bool ailang_map_si_has(ailang_map_si m, const char* k) {
    uint64_t mask = (uint64_t)(m->cap - 1);
    uint64_t h = ailang_hash_str(k) & mask;
    for (int64_t p = 0; p < m->cap; p++) {
        int64_t i = (int64_t)((h + (uint64_t)p) & mask);
        if (!m->occupied[i]) return false;
        if (strcmp(m->keys[i], k) == 0) return true;
    }
    return false;
}

static void ailang_print_map_si(ailang_map_si m) {
    printf("{");
    bool first = true;
    for (int64_t i = 0; i < m->cap; i++) {
        if (!m->occupied[i]) continue;
        if (!first) printf(", ");
        first = false;
        printf("\"%s\": %lld", m->keys[i] ? m->keys[i] : "", (long long) m->values[i]);
    }
    printf("}");
}
static void ailang_println_map_si(ailang_map_si m) { ailang_print_map_si(m); printf("\n"); }

/* -------- {str:str} map — same shape, both keys and values are strings.
 *
 * Useful for parsing flat JSON, config files, environment-style data. */
typedef struct {
    int64_t cap;
    int64_t len;
    const char** keys;
    const char** values;
    uint8_t* occupied;
} ailang_map_ss_storage;
typedef ailang_map_ss_storage* ailang_map_ss;

static ailang_map_ss ailang_map_ss_make(int64_t initial_cap) {
    int64_t cap = 8;
    while (cap < initial_cap) cap *= 2;
    ailang_map_ss m = (ailang_map_ss) GC_MALLOC(sizeof(ailang_map_ss_storage));
    m->cap = cap;
    m->len = 0;
    m->keys = (const char**) GC_MALLOC((size_t)cap * sizeof(const char*));
    m->values = (const char**) GC_MALLOC((size_t)cap * sizeof(const char*));
    m->occupied = (uint8_t*) GC_malloc_atomic((size_t)cap);
    memset(m->occupied, 0, (size_t)cap);
    return m;
}

static void ailang_map_ss_grow(ailang_map_ss m) {
    int64_t old_cap = m->cap;
    const char** old_keys = m->keys;
    const char** old_values = m->values;
    uint8_t* old_occupied = m->occupied;
    int64_t new_cap = old_cap * 2;
    m->cap = new_cap;
    m->keys = (const char**) GC_MALLOC((size_t)new_cap * sizeof(const char*));
    m->values = (const char**) GC_MALLOC((size_t)new_cap * sizeof(const char*));
    m->occupied = (uint8_t*) GC_malloc_atomic((size_t)new_cap);
    memset(m->occupied, 0, (size_t)new_cap);
    uint64_t mask = (uint64_t)(new_cap - 1);
    for (int64_t i = 0; i < old_cap; i++) {
        if (!old_occupied[i]) continue;
        const char* k = old_keys[i];
        uint64_t h = ailang_hash_str(k) & mask;
        for (int64_t p = 0; p < new_cap; p++) {
            int64_t j = (int64_t)((h + (uint64_t)p) & mask);
            if (!m->occupied[j]) {
                m->keys[j] = k;
                m->values[j] = old_values[i];
                m->occupied[j] = 1;
                break;
            }
        }
    }
}

static void ailang_map_ss_set(ailang_map_ss m, const char* k, const char* v) {
    if (m->len * 10 >= m->cap * 7) ailang_map_ss_grow(m);
    uint64_t mask = (uint64_t)(m->cap - 1);
    uint64_t h = ailang_hash_str(k) & mask;
    for (int64_t p = 0; p < m->cap; p++) {
        int64_t i = (int64_t)((h + (uint64_t)p) & mask);
        if (!m->occupied[i]) {
            m->keys[i] = k;
            m->values[i] = v;
            m->occupied[i] = 1;
            m->len++;
            return;
        }
        if (strcmp(m->keys[i], k) == 0) { m->values[i] = v; return; }
    }
}

static const char* ailang_map_ss_get(ailang_map_ss m, const char* k) {
    uint64_t mask = (uint64_t)(m->cap - 1);
    uint64_t h = ailang_hash_str(k) & mask;
    for (int64_t p = 0; p < m->cap; p++) {
        int64_t i = (int64_t)((h + (uint64_t)p) & mask);
        if (!m->occupied[i]) return "";
        if (strcmp(m->keys[i], k) == 0) return m->values[i];
    }
    return "";
}

static int64_t ailang_map_ss_len(ailang_map_ss m) { return m->len; }
static bool ailang_map_ss_has(ailang_map_ss m, const char* k) {
    uint64_t mask = (uint64_t)(m->cap - 1);
    uint64_t h = ailang_hash_str(k) & mask;
    for (int64_t p = 0; p < m->cap; p++) {
        int64_t i = (int64_t)((h + (uint64_t)p) & mask);
        if (!m->occupied[i]) return false;
        if (strcmp(m->keys[i], k) == 0) return true;
    }
    return false;
}

static void ailang_print_map_ss(ailang_map_ss m) {
    printf("{");
    bool first = true;
    for (int64_t i = 0; i < m->cap; i++) {
        if (!m->occupied[i]) continue;
        if (!first) printf(", ");
        first = false;
        printf("\"%s\": \"%s\"",
            m->keys[i] ? m->keys[i] : "",
            m->values[i] ? m->values[i] : "");
    }
    printf("}");
}
static void ailang_println_map_ss(ailang_map_ss m) { ailang_print_map_ss(m); printf("\n"); }

/* -------- keys / values for both map combos.
 * Return arrays of the appropriate element type. */
static ailang_arr_i64 ailang_map_ii_keys(ailang_map_ii m) {
    ailang_arr_i64 a;
    a.len = m->len;
    a.cap = m->len;
    a.data = (int64_t*) GC_malloc_atomic((size_t)(a.len > 0 ? a.len : 1) * sizeof(int64_t));
    int64_t n = 0;
    for (int64_t i = 0; i < m->cap; i++) if (m->occupied[i]) a.data[n++] = m->keys[i];
    return a;
}
static ailang_arr_i64 ailang_map_ii_values(ailang_map_ii m) {
    ailang_arr_i64 a;
    a.len = m->len;
    a.cap = m->len;
    a.data = (int64_t*) GC_malloc_atomic((size_t)(a.len > 0 ? a.len : 1) * sizeof(int64_t));
    int64_t n = 0;
    for (int64_t i = 0; i < m->cap; i++) if (m->occupied[i]) a.data[n++] = m->values[i];
    return a;
}
static ailang_arr_str ailang_map_si_keys(ailang_map_si m) {
    ailang_arr_str a;
    a.len = m->len;
    a.cap = m->len;
    a.data = (const char**) GC_MALLOC((size_t)(a.len > 0 ? a.len : 1) * sizeof(const char*));
    int64_t n = 0;
    for (int64_t i = 0; i < m->cap; i++) if (m->occupied[i]) a.data[n++] = m->keys[i];
    return a;
}
static ailang_arr_i64 ailang_map_si_values(ailang_map_si m) {
    ailang_arr_i64 a;
    a.len = m->len;
    a.cap = m->len;
    a.data = (int64_t*) GC_malloc_atomic((size_t)(a.len > 0 ? a.len : 1) * sizeof(int64_t));
    int64_t n = 0;
    for (int64_t i = 0; i < m->cap; i++) if (m->occupied[i]) a.data[n++] = m->values[i];
    return a;
}
static ailang_arr_str ailang_map_ss_keys(ailang_map_ss m) {
    ailang_arr_str a;
    a.len = m->len;
    a.cap = m->len;
    a.data = (const char**) GC_MALLOC((size_t)(a.len > 0 ? a.len : 1) * sizeof(const char*));
    int64_t n = 0;
    for (int64_t i = 0; i < m->cap; i++) if (m->occupied[i]) a.data[n++] = m->keys[i];
    return a;
}
static ailang_arr_str ailang_map_ss_values(ailang_map_ss m) {
    ailang_arr_str a;
    a.len = m->len;
    a.cap = m->len;
    a.data = (const char**) GC_MALLOC((size_t)(a.len > 0 ? a.len : 1) * sizeof(const char*));
    int64_t n = 0;
    for (int64_t i = 0; i < m->cap; i++) if (m->occupied[i]) a.data[n++] = m->values[i];
    return a;
}

/* Polymorphic indexing: `a[i]` codegens to `ailang_at(a, i)`. */
#define ailang_at(x, i) _Generic((x), \
    char*: ailang_str_at, \
    const char*: ailang_str_at, \
    ailang_bytes: bytes_at, \
    ailang_arr_i64: ailang_arr_i64_at, \
    ailang_arr_str: ailang_arr_str_at, \
    ailang_map_ii: ailang_map_ii_get, \
    ailang_map_si: ailang_map_si_get, \
    ailang_map_ss: ailang_map_ss_get)((x), (i))

#define keys(m) _Generic((m), \
    ailang_map_ii: ailang_map_ii_keys, \
    ailang_map_si: ailang_map_si_keys, \
    ailang_map_ss: ailang_map_ss_keys)((m))

#define values(m) _Generic((m), \
    ailang_map_ii: ailang_map_ii_values, \
    ailang_map_si: ailang_map_si_values, \
    ailang_map_ss: ailang_map_ss_values)((m))

/* Aggregate pretty-printers. `print` returns void so we can compose:
 *   println_arr_i64 = print + '\n'. */
static void ailang_print_arr_i64(ailang_arr_i64 a) {
    printf("[");
    for (int64_t i = 0; i < a.len; i++) {
        if (i > 0) printf(", ");
        printf("%lld", (long long) a.data[i]);
    }
    printf("]");
}
static void ailang_println_arr_i64(ailang_arr_i64 a) { ailang_print_arr_i64(a); printf("\n"); }

static void ailang_print_arr_str(ailang_arr_str a) {
    printf("[");
    for (int64_t i = 0; i < a.len; i++) {
        if (i > 0) printf(", ");
        printf("\"%s\"", a.data[i] ? a.data[i] : "");
    }
    printf("]");
}
static void ailang_println_arr_str(ailang_arr_str a) { ailang_print_arr_str(a); printf("\n"); }

static void ailang_print_map_ii(ailang_map_ii m) {
    printf("{");
    bool first = true;
    for (int64_t i = 0; i < m->cap; i++) {
        if (!m->occupied[i]) continue;
        if (!first) printf(", ");
        first = false;
        printf("%lld: %lld", (long long) m->keys[i], (long long) m->values[i]);
    }
    printf("}");
}
static void ailang_println_map_ii(ailang_map_ii m) { ailang_print_map_ii(m); printf("\n"); }

/* Dispatch print/println by argument type via C11 _Generic.
 *
 * Only types codegen actually produces are listed — we don't include
 * synonyms (`long long` is the same type as `int64_t` on every platform we
 * target, and listing both is a hard error in C11). All integer literals
 * we emit are wrapped in `INT64_C(...)` so they're already `int64_t`. */
#define print(x)   _Generic((x), \
    int64_t: ailang_print_i64, \
    int: ailang_print_int, \
    double: ailang_print_f64, \
    bool: ailang_print_bool, \
    char*: ailang_print_str, \
    const char*: ailang_print_str, \
    ailang_bytes: ailang_print_bytes, \
    ailang_arr_i64: ailang_print_arr_i64, \
    ailang_arr_str: ailang_print_arr_str, \
    ailang_map_ii: ailang_print_map_ii, \
    ailang_map_si: ailang_print_map_si, \
    ailang_map_ss: ailang_print_map_ss)(x)

#define println(x) _Generic((x), \
    int64_t: ailang_println_i64, \
    int: ailang_println_int, \
    double: ailang_println_f64, \
    bool: ailang_println_bool, \
    char*: ailang_println_str, \
    const char*: ailang_println_str, \
    ailang_bytes: ailang_println_bytes, \
    ailang_arr_i64: ailang_println_arr_i64, \
    ailang_arr_str: ailang_println_arr_str, \
    ailang_map_ii: ailang_println_map_ii, \
    ailang_map_si: ailang_println_map_si, \
    ailang_map_ss: ailang_println_map_ss)(x)
